name: Pre-commit check
permissions: {}
on:
  pull_request:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.14"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 2.2.0
          # Add poetry bin to PATH for following steps
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache pre-commit hooks
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.5.7

      - name: Install tflint for pre-commit
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.zip")" > tflint.zip
          unzip tflint.zip
          rm tflint.zip
          sudo mv tflint /usr/bin/

      - name: Install trivy for pre-commit
        run: |
          curl -L "$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/tags/v0.61.1 | grep -o -E -i -m 1 "https://.+?/trivy_.+?_Linux-64bit.tar.gz")" > trivy.tar.gz
          tar -xzf trivy.tar.gz trivy
          rm trivy.tar.gz
          sudo mv trivy /usr/bin/

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: no-commit-to-branch
